version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  face-detection:
    lang: dockerfile
    handler: ./functions/face-detection
    image: davidandw190/face-detection:v1
    environment:
      write_debug: true
      exec_timeout: '30s'
      read_timeout: 25
      write_timeout: 25
      RAW_BODY: true
    annotations:
      com.openfaas.scale.min: "2"
      com.openfaas.scale.max: "10"
      com.openfaas.scale.factor: "25%"
      com.openfaas.scale.zero: "false"
      com.openfaas.scale.target: "30"
    health_check:
      initial_delay_seconds: 30
      period_seconds: 5
      failure_threshold: 3

  face-emotion-detection:
    lang: dockerfile
    handler: ./functions/face-emotion-detection
    image: davidandw190/face-emotion-detection:v1
    environment:
      write_debug: true
      exec_timeout: '20s'
      read_timeout: 15
      write_timeout: 15
      RAW_BODY: true
    annotations:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "8"
      com.openfaas.scale.factor: "25%"
      com.openfaas.scale.zero: "false"
      com.openfaas.scale.target: "35"
    health_check:
      initial_delay_seconds: 20
      period_seconds: 5
      failure_threshold: 3

  face-gender-detection:
    lang: dockerfile
    handler: ./functions/face-gender-detection
    image: davidandw190/face-gender-detection:v1
    environment:
      write_debug: true
      exec_timeout: '20s'
      read_timeout: 15
      write_timeout: 15
      RAW_BODY: true
    annotations:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "8"
      com.openfaas.scale.factor: "25%"
      com.openfaas.scale.zero: "false"
      com.openfaas.scale.target: "35"
    health_check:
      initial_delay_seconds: 20
      period_seconds: 5
      failure_threshold: 3

  face-analysis-orchestrator:
    lang: dockerfile
    handler: ./workflows/face-analysis-orchestrator
    image: davidandw190/face-analysis-orchestrator:v1
    environment:
      write_debug: true
      exec_timeout: '90s'
      read_timeout: 85
      write_timeout: 85
      RAW_BODY: true
      GATEWAY_URL: "http://gateway.openfaas:8080"
      FACE_DETECTION_FUNCTION: "face-detection"
      GENDER_DETECTION_FUNCTION: "face-gender-detection"
      EMOTION_DETECTION_FUNCTION: "face-emotion-detection"
      REDIS_HOST: "redis-master.openfaas.svc.cluster.local"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_TTL: "300"
    annotations:
      com.openfaas.scale.min: "2"
      com.openfaas.scale.max: "15"
      com.openfaas.scale.factor: "30%"
      com.openfaas.scale.zero: "false"
      com.openfaas.scale.target: "25"
    health_check:
      initial_delay_seconds: 60
      period_seconds: 10
      failure_threshold: 3

  sentiment-analysis:
    lang: dockerfile
    handler: ./functions/sentiment-analysis
    image: davidandw190/sentiment-analysis:v1
    environment:
      write_debug: true
      exec_timeout: '30s'
      read_timeout: 25
      write_timeout: 25
    annotations:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"
      com.openfaas.scale.factor: "20%"
      com.openfaas.scale.zero: "true"
      com.openfaas.scale.target: "50"
    health_check:
      initial_delay_seconds: 30
      period_seconds: 5
      failure_threshold: 3

  multi-label-sentiment-analysis:
    lang: dockerfile
    handler: ./functions/multi-label-sentiment-analysis
    image: davidandw190/multi-label-sentiment-analysis:v1
    environment:
      write_debug: true
      exec_timeout: '45s'
      read_timeout: 40
      write_timeout: 40
    annotations:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"
      com.openfaas.scale.factor: "20%"
      com.openfaas.scale.zero: "true"
      com.openfaas.scale.target: "40"
    health_check:
      initial_delay_seconds: 45
      period_seconds: 5
      failure_threshold: 3

  text-classification:
    lang: dockerfile
    handler: ./functions/text-classification
    image: davidandw190/text-classification:v1
    environment:
      write_debug: true
      exec_timeout: '30s'
      read_timeout: 25
      write_timeout: 25
    annotations:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"
      com.openfaas.scale.factor: "20%"
      com.openfaas.scale.zero: "true"
      com.openfaas.scale.target: "45"
    health_check:
      initial_delay_seconds: 30
      period_seconds: 5
      failure_threshold: 3
